import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [snippetText, setSnippetText] = React.useState<string>('');
  const snippetaMutation = trpc.snippet.createSnippet.useMutation();
  const router = useRouter();

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setSnippetText(e.target.value);
  }

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (snippetText === '') return;

    const snippet = await snippetaMutation.mutateAsync({
      text: snippetText
    });

    router.push(`/snippets/${snippet?.id}`);
  }
  return (
    <>
      <Head>
        <title>PasteIt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel='icon' href='/pasteit.png' />
      </Head>
      <main className='container mx-auto min-h-screen flex flex-col justify-center items-center gap-4'>
        <h1 className='text-4xl font-extrabold leading-normal text-gray-50'>
          <span className='text-red-300'>Paste</span>It
        </h1>
        <form onSubmit={handleSubmit} className="text-center space-y-4">
          <textarea id="message" onChange={handleChange} value={snippetText as string} rows={4} className="block p-2.5 w-96 h-48 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 placeholder:text-black focus:outline-none" placeholder="Write your text here..." />
          <button type='submit' className="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none">Create</button>
        </form>
      </main>
    </>
  );
};

export default Home;
