import Head from 'next/head';
import { useRouter } from 'next/router'
import { trpc } from '../../utils/trpc';

const SnippetPage = () => {
    const router = useRouter();
    const id = router.query?.id as string

    const { isLoading, data } = trpc.snippet.getSnippet.useQuery({
        id
    });

    if (isLoading) {
        return <span>Loading data....</span>
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(data!.text)
    }

    const handleReturnHome = () => {
        router.push('/');
    }

    return (
        <>
            <Head>
                <title>{data && data.text}</title>
                <link rel='icon' href='/pasteit.png' />
                <meta name="description" content="Generated by create-t3-app" />
            </Head>

            <div className='container mx-auto min-h-screen flex flex-col justify-center items-center gap-4'>
                <h1 onClick={handleReturnHome} className='cursor-pointer text-2xl font-extrabold leading-normal text-gray-50'>
                    Snippet <span className='text-red-300'>{id}</span>
                </h1>
                <textarea disabled value={data && data.text} rows={4} className="block p-2.5 w-96 h-48 text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:outline-none" />
                <button type='submit' onClick={handleCopy} className="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none">Copy to clipboard</button>
            </div>
        </>
    )
}

export default SnippetPage